### PR TITLE
Enhanced user account functionality

### PR DESCRIPTION
**Pull request by Jkrzy**
Working towards fulfillment of #7 

We'll:
- Track additional `User` information in a `Profile` model. 
- Allow users to reset their passwords
- Allow `admins` to create user accounts via the Django admin interface.
- Establish django Groups for anticipated site roles.

Also tacking on [mailhog](https://github.com/mailhog/MailHog) to ease email testing in development environment.

Does _not_ include email functionality from a deployed Heroku environment. I'd like to tackle that in a separate issue as it will involve a bit more reworking of the settings/config than I think is called for here.

### CODE REVIEW

**Comment by Jkrzy** [comment]
Hey @annalee, ready for review when you have a chance, thanks!  Covers use cases described in #7. 

We're covering basic user creation functionality via the django admin and password resettability.

**Comment by Jkrzy** [comment]
An open question I have re: the `Profile` model. What kind of validation, if any, do we want to perform on a Phone Number field? @porta-antiporta, may want to weigh in on this.

**Comment by porta-antiporta** [comment]
Given:
* Users are created by an admin (after a request by a licensee)
* Very few users on this system (<100)

I wouldn't prioritize phone validation as part of this story (and likely not part of this engagement either).

**Comment by porta-antiporta** [comment]
At _most_ we'd have a `confirm` ur change feature when a user edits their phone number.  We would not get to the point of `verifying` the number is that users by sending a text/voice call etc.

**Comment by porta-antiporta** [comment]
_especially_ because we are aware of the future staffing plan for this system after the 18F engagement ends.

**Pull request merged**
